export const INITIAL_PLAYER = {
  name: "Commander",
  level: 1,
  hp: 100,
  maxHp: 100,
  energy: 50,
  maxEnergy: 50,
  experience: 0,
  credits: 1000,
  class: "Commander",
  avatar: "🎖️",
};

export const ENEMY_TYPES = {
  "Crystal Spider": { avatar: "🕷️", hp: 60, damage: 15 },
  "Gem Golem": { avatar: "💎", hp: 90, damage: 20 },
  "Cyber Thug": { avatar: "🦾", hp: 70, damage: 18 },
  Drone: { avatar: "🛸", hp: 50, damage: 12 },
  "Stone Guardian": { avatar: "🗿", hp: 100, damage: 25 },
  Wraith: { avatar: "👻", hp: 80, damage: 22 },
  Pirate: { avatar: "🏴‍☠️", hp: 85, damage: 20 },
  "Security Bot": { avatar: "🤖", hp: 75, damage: 16 },
};

export const MAP_LOCATIONS = [
  {
    id: 1,
    name: "Crystal Caverns",
    type: "dungeon",
    x: 20,
    y: 30,
    enemies: ["Crystal Spider", "Gem Golem"],
    background: "from-purple-900 to-indigo-900",
    icon: "🏔️",
  },
  {
    id: 2,
    name: "Neon District",
    type: "city",
    x: 60,
    y: 40,
    enemies: ["Cyber Thug", "Drone"],
    background: "from-pink-900 to-purple-900",
    icon: "🌆",
  },
  {
    id: 3,
    name: "Ancient Ruins",
    type: "dungeon",
    x: 80,
    y: 70,
    enemies: ["Stone Guardian", "Wraith"],
    background: "from-yellow-900 to-orange-900",
    icon: "🏛️",
  },
  {
    id: 4,
    name: "Space Port",
    type: "city",
    x: 40,
    y: 80,
    enemies: ["Pirate", "Security Bot"],
    background: "from-blue-900 to-gray-900",
    icon: "🚀",
  },
];

export const AVAILABLE_RECRUITS = [
  {
    id: 1,
    name: "Zara the Mystic",
    class: "Mage",
    hp: 80,
    maxHp: 80,
    energy: 70,
    maxEnergy: 70,
    cost: 500,
    recruited: false,
    avatar: "🔮",
    skills: ["Fireball", "Heal", "Lightning"],
  },
  {
    id: 2,
    name: "Rex Cyborg",
    class: "Tank",
    hp: 120,
    maxHp: 120,
    energy: 30,
    maxEnergy: 30,
    cost: 750,
    recruited: false,
    avatar: "🤖",
    skills: ["Shield Bash", "Taunt", "Repair"],
  },
  {
    id: 3,
    name: "Nova Scout",
    class: "Ranger",
    hp: 90,
    maxHp: 90,
    energy: 60,
    maxEnergy: 60,
    cost: 600,
    recruited: false,
    avatar: "🏹",
    skills: ["Quick Shot", "Stealth", "Multi-Shot"],
  },
  {
    id: 4,
    name: "Blade Dancer",
    class: "Assassin",
    hp: 85,
    maxHp: 85,
    energy: 80,
    maxEnergy: 80,
    cost: 800,
    recruited: false,
    avatar: "🗡️",
    skills: ["Backstab", "Poison", "Dash"],
  },
  {
    id: 5,
    name: "Dr. Synthesis",
    class: "Medic",
    hp: 70,
    maxHp: 70,
    energy: 90,
    maxEnergy: 90,
    cost: 650,
    recruited: false,
    avatar: "💉",
    skills: ["Mass Heal", "Revive", "Boost"],
  },
];
